config/routes.rb
@nil_class = Haoshijia::Application.routes.draw do

  resources :users
  resources :sessions, only: [:new, :create, :destroy]
  resources :rooms , only: [:show,:index]
  root to: "welcome#home"
  get '/signup', to: 'users#new'
  match '/signin',  to: 'sessions#new',         via: 'get'
  match '/signout', to: 'sessions#destroy',     via: 'delete'
  match '/rooms', to: 'rooms#index', via: 'get'

end
@nil_class

app/models/room.rb
class Room < ActiveRecord::Base
  validates_presence_of :title
  has_many :screenshots,  :dependent => :destroy



  searchable do
    text :title,:traffic,:life_assort,:scenery
    #,:other_desc,:detail
    time :updated_at
    string :publish_month
    boolean :available
    integer :state
    integer :screenshots_count

  end

  def publish_month
    updated_at.strftime("%B %Y")
  end



#def available?
#  state == :available
#end

  #查找本地图片路径，以便显示图片信息
  require 'find'
  def findpath(files)
    @path = "#{ENV["BUNDLE_GEMFILE"].sub(/Gemfile/,"")}public/photo/"
    small = []
    large = []
    Find.find(@path) do |path|
      unless FileTest.directory?(path)
        files.each do |file|

        if File.basename(path) == file.photo
          #p findfile = findfile.push("#{File.dirname(path)}/#{File.basename(path)}")
          # findfile[0,38] = "http://zuzher.com"
          a = File.dirname(path).split("/")
          b = (a.drop(a.index("public")+1)).join("/")

          small.push("/#{b}/small_#{File.basename(path)}")
          large.push("/#{b}/large_#{File.basename(path)}")
        end
          end
      end
    end
    return small,large
  end

  # 查找库中的图片名称
  def first_screen(style = :large)
    if self.screenshots.blank?
      '../zuzher/assets/default_room.png'
    else
      a = self.screenshots.to_a
        findpath(a)   #调用路径方法
    end
  end
end

app/models/screenshot.rb
#coding:utf-8
class Screenshot < ActiveRecord::Base
  belongs_to :room, :counter_cache => true
  default_scope   order('position')

end

app/models/user.rb
class User < ActiveRecord::Base
  before_save { self.email = email.downcase }
  before_create :create_remember_token
  validates :username, presence: true, length: {maximum: 50}
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-]+(\.[a-z]+)*\.[a-z]+\z/i
  validates :email, presence:   true,
            format:     { with: VALID_EMAIL_REGEX },
            uniqueness: { case_sensitive: false }
  validates :password, length: { minimum: 6 }
  has_secure_password

  def User.new_remember_token
    SecureRandom.urlsafe_base64
  end

  def User.encrypt(token)
    Digest::SHA1.hexdigest(token.to_s)
  end

  private
  def create_remember_token
    self.remember_token = User.encrypt(User.new_remember_token)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  include SessionsHelper
end

app/controllers/rooms_controller.rb
class RoomsController < ApplicationController
  def index
    #
    @search = Room.search do
      fulltext params[:query]
      with(:updated_at).less_than(Time.zone.now)
      #with(:available).equal_to(1)
      with(:state).equal_to(1)
      with(:screenshots_count).less_than(10)
      facet(:publish_month)
      with(:publish_month, params[:month]) if params[:month].present?
    end
    @rooms = @search.results
    respond_to do |format|
      format.html { render :action => "index" }
      format.xml  { render :xml => @rooms }
    end

  end





  def show
    @room = Room.find_by_id(params[:id])

  end


end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new

  end

  def destroy
    sign_out
    redirect_to root_path
  end

  def create
    user = User.find_by_email(params[:session][:email].downcase)
    if user && user.authenticate(params[:session][:password])
      sign_in user
      redirect_back_or user
    else
      flash.now[:error] = 'Invalid email/password combination' # Not quite right!
      render 'new'
    end
  end


end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]
  before_action :signed_in_user, only: [:index,:edit, :update]
  before_action :correct_user, only: [:edit, :update]
  before_action :admin_user,     only: :destroy

  # GET /users
  # GET /users.json
  def index
    @users = User.where.not(admin: true,state: false).paginate(page: params[:page])
  end

  # GET /users/1
  # GET /users/1.json
  def show
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(user_params)
    logger.info(@user.username)
    respond_to do |format|
      if @user.save
        sign_in @user
        format.html { redirect_to @user, notice: 'User was successfully created.' }
        format.json { render action: 'index', status: :created, location: @user }
      else
        format.html { render action: 'new' }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url }
      format.json { head :no_content }
    end
  end

  private
  def admin_user
    redirect_to(root_path) unless current_user.admin?
  end

  private
  def signed_in_user
    unless signed_in?
      store_location
      redirect_to signin_url, notice: "Please sign in."
    end
  end

  def correct_user
    @user = User.find(params[:id])
    redirect_to(root_path) unless current_user?(@user)
  end

  # Use callbacks to share common setup or constraints between actions.
  def set_user
    @user = User.find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def user_params
    params.require(:user).permit(:username, :mobile, :email, :password,
                                 :password_confirmation)
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def home
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/rooms_helper.rb
module RoomsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper

  def sign_in(user)
    remember_token = User.new_remember_token
    cookies.permanent[:remember_token] = remember_token
    user.update_attribute(:remember_token, User.encrypt(remember_token))
    self.current_user = user
  end

  def current_user=(user)
    @current_user = user
  end

  def current_user
    remember_token = User.encrypt(cookies[:remember_token])
    @current_user ||= User.find_by(remember_token: remember_token)

  end

  def current_user?(user)
    user == current_user
  end

  def signed_in?
    !current_user.nil?
  end

  def sign_out
    current_user.update_attribute(:remember_token,
                                  User.encrypt(User.new_remember_token))

    self.current_user = nil
    cookies.delete(:remember_token)
  end

  def redirect_back_or(default)
    redirect_to(session[:return_to] || default)
    session.delete(:return_to)
  end

  def store_location
    session[:return_to] = request.fullpath if request.get?
  end

end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/layouts/_footer.html.erb
<div class="panel-footer">
  <!--<div id="ToolBar">-->
  <!--<div id="footer">-->
  <div class="container">
    <p class="muted credit">
      <%= link_to "关于好时家" %>

    </p>

  </div>
</div>

app/views/layouts/_header.html.erb
<div class="header">
  <ul class="nav nav-pills pull-right">
    <li class="active"><%= link_to "首页", root_path %></li>
    <% if signed_in? %>
        <% if current_user.admin? %>
       <li><%= link_to "管理",users_path %></li>
            <% end %>
        <li>
          <%= link_to "登出", signout_path, method: "delete" %>
        </li>


        <li><%= link_to "设置", edit_user_path(current_user) %></li>


    <% else %>
        <li><%= link_to "登录", signin_path %></li>
        <li><%= link_to "注册", signup_path %></li>
    <% end %>

  </ul>
  <h3 class="text-muted">Project name</h3>
</div>

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
<script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
<![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>HAOSHIJIA</title>
  <%= stylesheet_link_tag "application", media: "all",
                          "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
  <%= render 'layouts/shim' %>
</head>
<body>

<div class="container">
  <%= render 'layouts/header' %>

  <%= yield %>

  <%= debug(params) if Rails.env.development? %>
</div>
<%= render 'layouts/footer' %>
</body>
</html>

app/views/rooms/index.html.erb
<% provide(:title, '全部房间') %>

<%= form_tag rooms_path, :method => :get do %>
    <p>

      <%#= hidden_field_tag :state, 1 %>
      <%= text_field_tag :query, params[:query] %>
      <%= submit_tag "Search", :name => nil %>
    </p>
<% end %>


      <table>
        <thead>
        <tr>
          <td>图</td>
          <td>标题</td>
          <td>创建日</td>
          <td>交通状况</td>
          <td>周边基础设施</td>
          <td>附近景点</td>
          <!--<td></td>-->
          <!--<td></td>-->
          <!--<td></td>-->

        </tr>
        </thead>
        <% @rooms.each do |room| %>
        <tr>
          <td><%= link_to image_tag(room.first_screen[0][0], alt: "Rails"), room_path(room) %></td>
          <td><%= link_to truncate(room.title, :length => 18), room_path(room) %></td>
          <td><%= room.created_at %></td>
          <td><%= room.traffic %></td>
          <td><%= room.life_assort %></td>
          <td><%= room.scenery %></td>
          <!--<td></td>-->
        </tr>
        <% end %>
      </table>



<div id="facets">
  <h3>Published</h3>
  <ul>
    <% for row in @search.facet(:publish_month).rows %>
        <li>
          <% if params[:month].blank? %>
              <%= link_to row.value, :month => row.value %> (<%= row.count %>)
          <% else %>
              <strong><%= row.value %></strong> (<%= link_to "remove", :month => nil %>)
          <% end %>
        </li>
    <% end %>
  </ul>
</div>

<%= will_paginate %>

app/views/rooms/show.html.erb
<p>
  <strong>title:</strong>
  <%= @room.title %>
  <%  @room.first_screen[1].each do |image| %>

  <%= image_tag image %>
      <% end %>
</p>

app/views/shared/_error_messages.html.erb
<% if @user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
        <% @user.errors.full_messages.each do |msg| %>
            <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
<% end %>

app/views/users/_form.html.erb
<%= form_for(@user, html: {class: "form-signin"}) do |f| %>
    <%= render 'shared/error_messages' %>
    <h2 class="form-signin-heading">注册</h2>

  <div class="field">
    <%= f.label :username %><br>
    <%= f.text_field :username %>
  </div>
  <div class="field">
    <%= f.label :mobile %><br>
    <%= f.text_field :mobile %>
  </div>
  <div class="field">
    <%= f.label :email %><br>
    <%= f.text_field :email %>
  </div>
    <div class="field">
    <%= f.label :password %>  <br>
    <%= f.password_field :password %>
    </div>

    <div class="field">
    <%= f.label :password_confirmation, "Confirmation" %>  <br>
    <%= f.password_field :password_confirmation %>
    </div>
    <div class="actions">
    <%= f.submit "Create my account", class: "btn btn-large btn-primary"%>
  </div>
<% end %>

app/views/users/_user.html.erb
<li>

  <% if current_user.admin? && !current_user?(user) %>
      <%= link_to user.username, user %>
      | <%= link_to "delete", user, method: :delete,
                    data: { confirm: "You sure?" } %>
  <% end %>
</li>

app/views/users/edit.html.erb
<% provide(:title, "编辑用户") %>


    <%= form_for(@user, html: {class: "form-signin"}) do |f| %>
    <h2 class="form-signin-heading">编辑用户</h2>
        <%= render 'shared/error_messages' %>


        <%= f.label "姓名" %>
        <%= f.text_field :username ,class: "input-block-level"%>

        <%= f.label "电话" %>
        <%= f.text_field :mobile,class: "input-block-level" %>

        <%= f.label "email" %>
        <%= f.text_field :email,class: "input-block-level" %>

        <%= f.label :password %>
        <%= f.password_field :password,class: "input-block-level" %>

        <%= f.label :password_confirmation, "Confirm Password" %>
        <%= f.password_field :password_confirmation,class: "input-block-level" %>

        <%= f.submit "保存", class: "btn btn-large btn-primary" %>
    <% end %>

app/views/users/index.html.erb
<% provide(:title, '全部用户') %>
<h1>All users</h1>

<ul class="users">

      <%= render @users %>

</ul>
<%= will_paginate %>

app/views/users/new.html.erb
<% provide(:title, "用户注册") %>
<%= render 'form' %>

<%= link_to 'Back', users_path %>

app/views/users/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Username:</strong>
  <%= @user.username %>
</p>

<p>
  <strong>Mobile:</strong>
  <%= @user.mobile %>
</p>

<p>
  <strong>Email:</strong>
  <%= @user.email %>
</p>

app/views/welcome/home.html.erb
<h1>Welcome#home</h1>
<p>Find me in app/views/welcome/home.html.erb</p>